//! `cargo xtask docs [--check]`: the generated documentation.
//!
//! * `CONFIG.md`, the configuration reference: `docs/CONFIG.template.md`
//!   with the generated parts filled in, namely every setting of
//!   `assets/default.toml` with its default and its comment ([`settings`]),
//!   the theme elements with their parents, the built-in themes and the
//!   default palette ([`theme`]), and the pager's key bindings
//!   (`emde::pager::keymap`).
//! * The key bindings in `README.md`, between the `BEGIN GENERATED keys`
//!   and `END GENERATED keys` comments.
//! * The man page `$CARGO_TARGET_DIR/man/emde.1` and bash, zsh and fish
//!   completions in `$CARGO_TARGET_DIR/completions/`, from `emde::cli::Cli`
//!   ([`man`]).
//!
//! Every TOML example in `README.md` and `CONFIG.md` must load through
//! emde's own configuration loader without a single warning ([`examples`]),
//! so the documentation cannot describe settings that do not exist.
//!
//! With `--check` nothing is written: the task fails when `CONFIG.md` or the
//! README's key table is not exactly what the generator produces (`cargo
//! xtask ci` runs this), and the man page and completions are only rendered
//! in memory.

pub(crate) mod examples;
mod man;
mod markdown;
mod settings;
mod theme;

use std::fs;
use std::path::Path;

use emde::pager::keymap;

/// The configuration reference's template, relative to the repository root.
const CONFIG_TEMPLATE: &str = "docs/CONFIG.template.md";
/// Where the configuration reference goes.
const CONFIG_MD: &str = "CONFIG.md";
/// The README, which holds a generated key table.
const README_MD: &str = "README.md";
/// The generated block of the README that lists the key bindings.
const README_KEYS: &str = "keys";

/// Regenerate the documentation, or with `check` verify it is up to date.
pub(crate) fn run(check: bool) -> Result<(), String> {
    let root = crate::repo_root()?;
    let config_md = config_reference(&root)?;
    let readme_path = root.join(README_MD);
    let readme = read(&readme_path)?;
    let readme = markdown::replace_generated(&readme, README_KEYS, &keymap::markdown())
        .map_err(|e| format!("{README_MD}: {e}"))?;
    examples::check(README_MD, &readme)?;
    examples::check(CONFIG_MD, &config_md)?;

    let mut stale = Vec::new();
    for (rel, text) in [(CONFIG_MD, &config_md), (README_MD, &readme)] {
        let path = root.join(rel);
        if fs::read_to_string(&path).ok().as_deref() == Some(text.as_str()) {
            continue;
        }
        if check {
            stale.push(rel);
        } else {
            fs::write(&path, text).map_err(|e| format!("{}: {e}", path.display()))?;
            eprintln!("xtask: wrote {rel}");
        }
    }

    if check {
        // Not checked in: only make sure they can still be generated.
        man::man_page()?;
        man::completions()?;
    } else {
        let target = crate::target_dir()?;
        let page = man::write_man_page(&target.join("man"))?;
        eprintln!("xtask: wrote {}", page.display());
        for path in man::write_completions(&target.join("completions"))? {
            eprintln!("xtask: wrote {}", path.display());
        }
    }

    if stale.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "generated documentation is out of date: {} (run `cargo xtask docs`)",
            stale.join(", ")
        ))
    }
}

/// `CONFIG.md`: the template with every `{{name}}` line replaced by the
/// generated part of that name.
fn config_reference(root: &Path) -> Result<String, String> {
    let template = read(&root.join(CONFIG_TEMPLATE))?;
    let default_toml = read(&root.join("assets/default.toml"))?;
    let sections = settings::parse(&default_toml).map_err(|e| format!("default.toml: {e}"))?;
    let themes = theme::Themes::load(root)?;
    let parts = [
        ("settings", settings::markdown(&sections)?),
        ("themes", themes.builtin_markdown()?),
        ("palette", themes.palette_markdown()?),
        ("elements", themes.elements_markdown()?),
        ("keys", keymap::markdown()),
    ];
    let body = markdown::fill_template(&template, &parts)
        .map_err(|e| format!("{CONFIG_TEMPLATE}: {e}"))?;
    Ok(format!(
        "<!-- Generated by `cargo xtask docs` from {CONFIG_TEMPLATE}, assets/default.toml, \
         assets/themes/, src/theme/element.rs and src/pager/keymap.rs. Do not edit: \
         change those and run `cargo xtask docs`. -->\n\n{body}"
    ))
}

/// Read a UTF-8 file, with the path in the error.
fn read(path: &Path) -> Result<String, String> {
    fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))
}

#[cfg(test)]
mod tests {
    /// `cargo test` catches stale documentation too, not only `cargo xtask
    /// ci`: after a change to the key table, the defaults or the theme
    /// elements, run `cargo xtask docs`.
    #[test]
    fn generated_documentation_is_up_to_date() {
        if let Err(e) = super::run(true) {
            panic!("{e}");
        }
    }
}
