//! Images: decoding, text-mode rasterising and graphics protocol encoders
//! (kitty placeholders/classic, iTerm2 OSC 1337, sixel).
//!
//! Everything here is pure: functions turn file bytes into pixels, pixels
//! into text cells, and pixels or files into escape-sequence bytes. Nothing
//! writes to the terminal; the stream writer and the pager decide where and
//! when the bytes go. [`decode`] and [`png`] need the `images` feature,
//! [`sixel`] the `sixel` feature; everything else is always built.
//!
//! # From a Markdown image to the screen
//!
//! 1. **Size** from the file header only ([`decode::dimensions`], then
//!    [`size::figure_cells`]), so layout never waits for a decode and a
//!    figure never reflows when its pixels arrive.
//! 2. **Choose** the graphics path once per run with [`select::choose`] and
//!    the block glyphs with [`select::block_glyphs`].
//! 3. **Decode** on a worker thread with [`decode::decode`]: the pixel limit
//!    is enforced before any pixel is allocated, and decoder panics are
//!    caught.
//! 4. **Render** for the chosen path:
//!    * blocks: [`raster::rasterize`] gives a grid of glyph cells;
//!    * kitty placeholders: [`kitty::transmit_placeholder`] once, then
//!      [`kitty::placeholder_row`] is the text of each row;
//!    * kitty classic: [`kitty::transmit`] once, [`kitty::place`] after
//!      every frame;
//!    * iTerm2: [`iterm::inline_image`] of the original file or a PNG
//!      ([`png::encode`]);
//!    * sixel: [`sixel::encode`] of the image composited and scaled to its
//!      cell box with [`resize_onto`].
//!
//! # Redraw rules (plan §7)
//!
//! | Path | Upload | Scrolling, partly visible | Resize, exit |
//! |---|---|---|---|
//! | blocks | none: rows are text | free; rows are cut like text | re-raster |
//! | kitty placeholders | `a=T,U=1` ([`kitty::transmit_placeholder`]); rows show blocks until it is sent | free: rows are text | a new [`kitty::ImageId`] (ids are never reused); `a=d,d=I` on exit |
//! | kitty classic (never in tmux) | `a=t` once ([`kitty::transmit`]) | re-place after each frame ([`kitty::place`], cropped with [`size::visible_pixel_rows`]) | `d=i` when off-screen, `d=I` on exit ([`kitty::delete`]) |
//! | iTerm2 OSC 1337 | none | blocks while scrolling, pixels [`SCROLL_DEBOUNCE`] after the last scroll; a cropped slice when partly visible | redraw |
//! | sixel | none | as iTerm2; crops end on whole sixel bands ([`sixel::crop_rows`]) | redraw |
//!
//! Two rules hold for every kitty command: it carries `q=2`, so the
//! terminal never answers (a late reply would reach the key reader as key
//! presses), and inside tmux it is wrapped chunk by chunk in the passthrough
//! DCS ([`Passthrough::Tmux`]), because tmux turns an unwrapped `ESC _G`
//! into a pane title.

pub mod b64;
#[cfg(feature = "images")]
pub mod decode;
pub mod glyphs;
pub mod iterm;
pub mod kitty;
#[cfg(feature = "images")]
pub mod png;
pub mod raster;
mod resample;
pub mod select;
#[cfg(feature = "sixel")]
pub mod sixel;
pub mod size;
pub mod tmux;

/// Unicode tables generated by `cargo xtask gen`; never edit them by hand.
mod r#gen {
    pub(crate) mod diacritics;
    pub(crate) mod octants;
    #[cfg(test)]
    pub(crate) mod sextants;
}

use std::ops::Range;
use std::time::Duration;

pub use resample::{resize, resize_onto};

use crate::style::Rgb;
use crate::term::Graphics;

/// An 8-bit RGBA image: sRGB colour with straight (not premultiplied)
/// alpha, stored row by row from the top, 4 bytes per pixel.
///
/// The fields are public so images are easy to build. A value whose
/// `pixels` length is not exactly `width × height × 4` is *invalid*; every
/// function in this module treats an invalid image as an empty one instead
/// of panicking.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Rgba {
    /// Width in pixels.
    pub width: u32,
    /// Height in pixels.
    pub height: u32,
    /// `width × height` pixels of `[r, g, b, a]`.
    pub pixels: Vec<u8>,
}

impl Rgba {
    /// An image from its parts, or `None` if the buffer does not match the size.
    pub fn new(width: u32, height: u32, pixels: Vec<u8>) -> Option<Rgba> {
        let image = Rgba {
            width,
            height,
            pixels,
        };
        image.is_valid().then_some(image)
    }

    /// An image filled with one colour, or `None` if its buffer cannot be
    /// allocated.
    pub fn filled(width: u32, height: u32, rgba: [u8; 4]) -> Option<Rgba> {
        let len = Rgba::byte_len(width, height)?;
        let mut pixels = Vec::new();
        pixels.try_reserve_exact(len).ok()?;
        pixels.extend(rgba.iter().copied().cycle().take(len));
        Some(Rgba {
            width,
            height,
            pixels,
        })
    }

    /// The buffer length of a `width × height` image, if a buffer that long
    /// can exist (at most `isize::MAX` bytes).
    pub fn byte_len(width: u32, height: u32) -> Option<usize> {
        let len = usize::try_from(width)
            .ok()?
            .checked_mul(usize::try_from(height).ok()?)?
            .checked_mul(4)?;
        isize::try_from(len).is_ok().then_some(len)
    }

    /// Whether the buffer length matches the size.
    pub fn is_valid(&self) -> bool {
        Rgba::byte_len(self.width, self.height) == Some(self.pixels.len())
    }

    /// Whether there is nothing to draw: no pixels, or an invalid image.
    pub fn is_empty(&self) -> bool {
        self.pixels.is_empty() || !self.is_valid()
    }

    /// The pixel at `(x, y)`: transparent black outside the image.
    pub fn pixel(&self, x: u32, y: u32) -> [u8; 4] {
        if x >= self.width || y >= self.height || !self.is_valid() {
            return [0; 4];
        }
        let i = (y as usize * self.width as usize + x as usize) * 4;
        match self.pixels.get(i..i + 4) {
            Some(&[r, g, b, a]) => [r, g, b, a],
            _ => [0; 4],
        }
    }

    /// Whether any pixel is less than fully opaque.
    pub fn has_alpha(&self) -> bool {
        self.pixels
            .as_chunks::<4>()
            .0
            .iter()
            .any(|&[_, _, _, a]| a != 255)
    }

    /// The pixel rows in `rows` (clamped to the image) as a new image.
    pub fn crop_rows(&self, rows: Range<u32>) -> Rgba {
        if !self.is_valid() {
            return Rgba::default();
        }
        let end = rows.end.min(self.height);
        let start = rows.start.min(end);
        let stride = self.width as usize * 4;
        let pixels = self
            .pixels
            .get(start as usize * stride..end as usize * stride)
            .unwrap_or_default()
            .to_vec();
        Rgba {
            width: self.width,
            height: end - start,
            pixels,
        }
    }

    /// The image composited onto an opaque `background`, so every pixel is
    /// opaque. Blending happens on sRGB values, as browsers do, so
    /// anti-aliased edges look the way the image's author intended. To
    /// composite and scale in one go, use [`resize_onto`], which blends
    /// before it averages.
    pub fn flatten(&self, background: Rgb) -> Rgba {
        if !self.is_valid() {
            return Rgba::default();
        }
        let bg = [background.0, background.1, background.2];
        let mut pixels = self.pixels.clone();
        for [r, g, b, a] in pixels.as_chunks_mut::<4>().0 {
            if *a != 255 {
                for (c, under) in [r, g, b].into_iter().zip(bg) {
                    *c = blend_srgb(*c, under, *a);
                }
                *a = 255;
            }
        }
        Rgba {
            width: self.width,
            height: self.height,
            pixels,
        }
    }
}

/// `c` over `under` at opacity `alpha`, blended on sRGB values and
/// rounded to the nearest byte.
pub(crate) fn blend_srgb(c: u8, under: u8, alpha: u8) -> u8 {
    let a = u32::from(alpha);
    let mixed = (u32::from(c) * a + u32::from(under) * (255 - a) + 127) / 255;
    u8::try_from(mixed).unwrap_or(u8::MAX)
}

/// How escape sequences reach the terminal.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Default)]
pub enum Passthrough {
    /// Written as they are.
    #[default]
    Direct,
    /// Wrapped in tmux's passthrough DCS (`ESC Ptmux; … ESC \`) so they
    /// reach the terminal outside tmux. Needs `allow-passthrough on`.
    Tmux,
}

impl Passthrough {
    /// Append one complete escape sequence to `out`, wrapped when needed.
    pub fn push(self, seq: &[u8], out: &mut Vec<u8>) {
        match self {
            Passthrough::Direct => out.extend_from_slice(seq),
            Passthrough::Tmux => tmux::wrap_into(seq, out),
        }
    }
}

/// How a graphics path behaves on screen (plan §7).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum GfxKind {
    /// Rows are ordinary text cells (block glyphs).
    Text,
    /// Rows are text that refers to pixels uploaded once (kitty Unicode
    /// placeholders).
    Placeholder,
    /// Pixels painted over reserved blank rows after each frame (kitty
    /// classic placements, iTerm2, sixel).
    Overlay,
}

impl GfxKind {
    /// The kind of a graphics path; `None` when images are not drawn at all.
    pub const fn of(graphics: Graphics) -> Option<GfxKind> {
        match graphics {
            Graphics::None => None,
            Graphics::Blocks => Some(GfxKind::Text),
            Graphics::KittyPlaceholders => Some(GfxKind::Placeholder),
            Graphics::KittyClassic | Graphics::Iterm | Graphics::Sixel => Some(GfxKind::Overlay),
        }
    }

    /// Whether images move with the text, so a scroll can use the scroll
    /// region fast path. Overlays must be redrawn instead.
    pub const fn scrolls_with_text(self) -> bool {
        matches!(self, GfxKind::Text | GfxKind::Placeholder)
    }
}

/// How long iTerm2 and sixel images show as blocks after the last scroll
/// before their pixels are sent again.
pub const SCROLL_DEBOUNCE: Duration = Duration::from_millis(120);

/// A pixel graphics protocol encoded by this module.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Protocol {
    /// kitty graphics shown through Unicode placeholder text.
    KittyPlaceholders,
    /// kitty graphics with classic placements (never inside tmux).
    KittyClassic,
    /// iTerm2 inline images (OSC 1337).
    Iterm,
    /// DEC sixel, direct or drawn by tmux itself.
    Sixel,
}

impl Protocol {
    /// The protocol of a graphics path; `None` for blocks and no images.
    pub const fn from_graphics(graphics: Graphics) -> Option<Protocol> {
        match graphics {
            Graphics::KittyPlaceholders => Some(Protocol::KittyPlaceholders),
            Graphics::KittyClassic => Some(Protocol::KittyClassic),
            Graphics::Iterm => Some(Protocol::Iterm),
            Graphics::Sixel => Some(Protocol::Sixel),
            Graphics::None | Graphics::Blocks => None,
        }
    }

    /// The graphics path this protocol implements.
    pub const fn graphics(self) -> Graphics {
        match self {
            Protocol::KittyPlaceholders => Graphics::KittyPlaceholders,
            Protocol::KittyClassic => Graphics::KittyClassic,
            Protocol::Iterm => Graphics::Iterm,
            Protocol::Sixel => Graphics::Sixel,
        }
    }

    /// How the protocol's images behave on screen.
    pub const fn kind(self) -> GfxKind {
        match self {
            Protocol::KittyPlaceholders => GfxKind::Placeholder,
            Protocol::KittyClassic | Protocol::Iterm | Protocol::Sixel => GfxKind::Overlay,
        }
    }

    /// Whether the image must be sent again after each scroll, with blocks
    /// shown for [`SCROLL_DEBOUNCE`] in between. kitty keeps images in the
    /// terminal, so re-placing them is cheap and needs no debounce.
    pub const fn debounces_scrolling(self) -> bool {
        matches!(self, Protocol::Iterm | Protocol::Sixel)
    }

    /// Whether the protocol works inside tmux: placeholders through
    /// passthrough, sixel drawn by tmux itself. tmux neither moves the outer
    /// cursor for passthrough bytes nor redraws them, so classic placements
    /// and OSC 1337 land in the wrong place and get erased.
    pub const fn works_in_tmux(self) -> bool {
        matches!(self, Protocol::KittyPlaceholders | Protocol::Sixel)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn image(width: u32, height: u32, pixels: &[[u8; 4]]) -> Rgba {
        Rgba::new(width, height, pixels.concat()).unwrap()
    }

    #[test]
    fn construction_validates_the_buffer() {
        assert!(Rgba::new(2, 1, vec![0; 8]).is_some());
        assert!(Rgba::new(2, 1, vec![0; 7]).is_none());
        assert!(Rgba::new(0, 5, Vec::new()).is_some());
        let odd = Rgba {
            width: 3,
            height: 3,
            pixels: vec![1; 5],
        };
        assert!(!odd.is_valid());
        assert!(odd.is_empty());
        assert_eq!(odd.pixel(0, 0), [0; 4]);
        assert_eq!(odd.crop_rows(0..2), Rgba::default());
        assert_eq!(odd.flatten(Rgb(1, 2, 3)), Rgba::default());
        assert_eq!(Rgba::byte_len(u32::MAX, u32::MAX), None);
        assert_eq!(Rgba::byte_len(3, 2), Some(24));
        // Fits in `usize` but not in any allocation (over `isize::MAX`).
        assert_eq!(Rgba::byte_len(u32::MAX, 1 << 30), None);
        assert_eq!(Rgba::filled(u32::MAX, 1 << 30, [0; 4]), None);
    }

    #[test]
    fn srgb_blending() {
        assert_eq!(blend_srgb(200, 10, 255), 200);
        assert_eq!(blend_srgb(200, 10, 0), 10);
        assert_eq!(blend_srgb(255, 0, 128), 128);
        assert_eq!(blend_srgb(0, 255, 128), 127);
        for (c, under, a) in [(0, 0, 77), (255, 255, 1), (9, 250, 200)] {
            let exact =
                (f64::from(c) * f64::from(a) + f64::from(under) * f64::from(255 - a)) / 255.0;
            assert_eq!(
                blend_srgb(c, under, a),
                exact.round() as u8,
                "{c} {under} {a}"
            );
        }
    }

    #[test]
    fn filled_and_pixels() {
        let img = Rgba::filled(3, 2, [1, 2, 3, 4]).unwrap();
        assert_eq!(img.pixels.len(), 24);
        assert_eq!(img.pixel(2, 1), [1, 2, 3, 4]);
        assert_eq!(img.pixel(3, 0), [0; 4]);
        assert_eq!(img.pixel(0, 2), [0; 4]);
        assert!(img.has_alpha());
        assert!(!Rgba::filled(1, 1, [9, 9, 9, 255]).unwrap().has_alpha());
    }

    #[test]
    fn crop_rows_clamps() {
        let img = image(1, 3, &[[1, 0, 0, 255], [2, 0, 0, 255], [3, 0, 0, 255]]);
        let mid = img.crop_rows(1..2);
        assert_eq!((mid.width, mid.height), (1, 1));
        assert_eq!(mid.pixel(0, 0), [2, 0, 0, 255]);
        let tail = img.crop_rows(2..10);
        assert_eq!(tail.height, 1);
        assert_eq!(tail.pixel(0, 0), [3, 0, 0, 255]);
        let none = img.crop_rows(5..9);
        assert_eq!(none.height, 0);
        assert!(none.pixels.is_empty());
        #[allow(clippy::reversed_empty_ranges)]
        let backwards = img.crop_rows(2..1);
        assert_eq!(backwards.height, 0);
    }

    #[test]
    fn flatten_blends_in_srgb() {
        let img = image(
            3,
            1,
            &[[255, 255, 255, 255], [255, 255, 255, 0], [255, 0, 0, 128]],
        );
        let flat = img.flatten(Rgb(0, 0, 255));
        assert!(!flat.has_alpha());
        assert_eq!(flat.pixel(0, 0), [255, 255, 255, 255]);
        assert_eq!(flat.pixel(1, 0), [0, 0, 255, 255]);
        assert_eq!(flat.pixel(2, 0), [128, 0, 127, 255]);
    }

    #[test]
    fn passthrough_wraps_only_for_tmux() {
        let mut direct = Vec::new();
        Passthrough::Direct.push(b"\x1b_Gq=2\x1b\\", &mut direct);
        assert_eq!(direct, b"\x1b_Gq=2\x1b\\");
        let mut wrapped = Vec::new();
        Passthrough::Tmux.push(b"\x1b_Gq=2\x1b\\", &mut wrapped);
        assert_eq!(wrapped, b"\x1bPtmux;\x1b\x1b_Gq=2\x1b\x1b\\\x1b\\");
    }

    #[test]
    fn protocol_table() {
        for g in [
            Graphics::KittyPlaceholders,
            Graphics::KittyClassic,
            Graphics::Iterm,
            Graphics::Sixel,
        ] {
            let p = Protocol::from_graphics(g).unwrap();
            assert_eq!(p.graphics(), g);
            assert_eq!(GfxKind::of(g), Some(p.kind()));
        }
        assert_eq!(Protocol::from_graphics(Graphics::Blocks), None);
        assert_eq!(GfxKind::of(Graphics::Blocks), Some(GfxKind::Text));
        assert_eq!(GfxKind::of(Graphics::None), None);
        assert!(GfxKind::Placeholder.scrolls_with_text());
        assert!(!GfxKind::Overlay.scrolls_with_text());
        assert!(Protocol::Iterm.debounces_scrolling());
        assert!(!Protocol::KittyClassic.debounces_scrolling());
        assert!(Protocol::KittyPlaceholders.works_in_tmux());
        assert!(!Protocol::Iterm.works_in_tmux());
        assert!(!Protocol::KittyClassic.works_in_tmux());
    }
}
